import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm,mkdir,writeFile,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Draft,defaults,composePlugins,parseRows,withSkillRoots} from '../plugin/config.mjs';
import {writeJson,readJson,serialQueue} from '../plugin/store.mjs';
import {migrate,assertRevision,adoptCandidate,ownsPreset} from '../plugin/modes.mjs';
import {presetStore,migrateLegacyDirectories} from '../plugin/presets.mjs';
import {observeSession} from '../plugin/host.mjs';
/** Shipped plugin rows of one built-in preset, read from the installed Web bundle. */
const source=async kind=>parseRows(await readFile(`node_modules/@deepseek-ai/dsh-web-app/presets/${kind}.patch.yml`,'utf8'))[0].insert[0].config.plugins;
const row=(rows,id)=>rows.find(r=>r.id===id);
test('all four bases preserve platform conditions, creator skills, persistent shell and presentation',async()=>{
 const standard=await source('standard');for(const kind of ['standard','ptc','minimal','cordis']){const base=await source(kind),draft=defaults(kind);draft.instructions='先给结论';const rows=composePlugins(base,draft,0,standard);assert(JSON.stringify(rows).includes('先给结论'));assert.notDeepEqual(rows,base);if(kind==='minimal'){assert(row(rows,'persistent-shell'));assert.equal(row(rows,'persona').config.complete,true);}else{assert.equal(typeof row(rows,'tool-pwsh').disabled.__jsExpr,'string');}if(kind==='cordis'){assert.equal(typeof row(rows,'tool-plugin-manager').disabled.__jsExpr,'string');assert.match(row(rows,'skill-filesystem').config.customSkillDirs[0].__jsExpr,/dsh-agent-preset\/package\.json/);}if(kind==='ptc')assert.equal(row(rows,'tool-presentation').config.mode,'ptc');}
});
test('composition never mutates the base rows it reads',async()=>{const base=await source('standard'),copy=structuredClone(base);const d=defaults();d.tools.files=false;composePlugins(base,d);assert.deepEqual(base,copy);});
test('minimal can add capabilities without replacing the persistent terminal',async()=>{const d=defaults('minimal');d.tools.files=true;d.presentation='ptc';const rows=composePlugins(await source('minimal'),d,1,await source('standard'));for(const id of ['persistent-shell','tool-fs','tool-skill','skill-filesystem','tool-presentation'])assert(row(rows,id),id);assert(!row(rows,'tool-bash'));});
test('disabled tool groups and MCP contribute only the selected capabilities',async()=>{const d=defaults();d.tools.files=false;d.tools.subagent=false;d.defaultSkills=false;d.mcp=[{id:'files',command:'/usr/bin/node',args:['server.mjs'],enabled:true},{id:'off',command:'node',args:[],enabled:false}];const rows=composePlugins(await source('standard'),d);for(const id of ['tool-fs','tool-fs-search','delegation'])assert.equal(row(rows,id).disabled,true);assert.equal(row(rows,'workbench-mcp-files').config.failOnStartupError,true);assert(!row(rows,'workbench-mcp-off'));assert.equal(row(rows,'skill-filesystem').config.includeDefaultRoots,false);assert.deepEqual(row(rows,'skill-filesystem').config.customSkillDirs,[]);});
test('creator plugin manager is disabled only when the mode turns it off',async()=>{const d=defaults('cordis');d.pluginManager=false;assert.equal(row(composePlugins(await source('cordis'),d),'tool-plugin-manager').disabled,true);});
test('Skill roots are added at materialization and require skill-filesystem',async()=>{const rows=composePlugins(await source('standard'),defaults());const out=withSkillRoots(rows,['/account/skills/a']);assert.deepEqual(row(out,'skill-filesystem').config.customSkillDirs.at(-1),'/account/skills/a');assert.equal(row(rows,'skill-filesystem').config.customSkillDirs.includes('/account/skills/a'),false);assert.throws(()=>withSkillRoots([{id:'persona',name:'x'}],['/r']),/skill-filesystem/);});
test('invalid fields, duplicate services, and evolution without observation are rejected',()=>{const d=defaults();const m={id:'same',command:'node',args:[],enabled:true};for(const patch of [{label:''},{mcp:[m,m]},{mcp:[{...m,id:'../escape'}]},{unexpected:true},{observe:false,evolution:{enabled:true,goal:''}},{instructions:'{{unknown}}'},{pluginManager:true}])assert.throws(()=>Draft.parse({...d,...patch}));});
test('legacy migration preserves preset identity and isolated drafts',()=>{const d={label:'旧配置',tools:defaults().tools,skills:[],mcp:[]};const old={schema:1,draft:d,versions:[{id:'old-v1',label:d.label,createdAt:'2026-09-01',config:d}],lastError:null};const migrated=migrate(old,'old-v1');assert.equal(migrated.modes.length,5);const legacy=migrated.modes[4];assert.equal(legacy.current,'old-v1');assert.equal(legacy.draft.defaultSkills,false);assert(ownsPreset(legacy,'old-v1'));legacy.draft.tools.files=false;assert(migrated.modes[0].draft.tools.files);assert.deepEqual(migrate(migrated,'old-v1'),migrated);assert.equal(old.draft.tools.files,true);assert.throws(()=>migrate({schema:99},'standard'));});
test('stale or unverified candidates cannot overwrite a draft',()=>{const mode=migrate(null,'standard').modes[0];mode.draft.evolution.enabled=true;mode.candidates=[{id:'c',status:'pending',basePreset:'standard',baseRevision:0,config:{...defaults(),instructions:'improve'},evidence:null}];assert.throws(()=>adoptCandidate(mode,'c'),/证据/);mode.candidates[0].evidence={baseline:'before',candidate:'after',sessionId:'s'};assertRevision(mode,0);mode.draftRevision=1;assert.throws(()=>adoptCandidate(mode,'c'),/草稿/);mode.draftRevision=0;mode.current='new';assert.throws(()=>adoptCandidate(mode,'c'),/基准/);mode.current='standard';adoptCandidate(mode,'c');assert.equal(mode.draft.instructions,'improve');assert.equal(mode.draftRevision,1);assert.throws(()=>adoptCandidate(mode,'c'),/已采用/);});
test('observation uses actual selected preset, request and tool-role error flag',()=>{assert.equal(observeSession({meta:{agentPreset:'standard'},events:[]}).model,null);const result=observeSession({meta:{agentPreset:'standard'},events:[{type:'agent-preset/selected',data:{agentPreset:'custom'}},{type:'request/header',data:{header:{config:{provider:'deepseek',model:'actual-model'}}}},{type:'tool/result',data:{message:{role:'tool',content:[],isError:true}}},{type:'tool/result',data:{message:{role:'tool',content:[]},error:{code:'bad'}}},{type:'tool/result',data:{message:{role:'tool',content:[]}}}]});assert.equal(result.presetId,'custom');assert.equal(result.model,'actual-model');assert.equal(result.toolCalls,3);assert.equal(result.toolErrors,2);});
test('atomic records and serialized failures retain the next operation',async()=>{const dir=await mkdtemp(join(tmpdir(),'workbench-store-'));try{const f=join(dir,'state.json');await writeJson(f,{version:1});assert.deepEqual(await readJson(f,null),{version:1});const queue=serialQueue();const order=[];const first=queue(async()=>{order.push(1);throw Error('rejected');});const second=queue(async()=>{order.push(2);await writeJson(f,{version:2});});await assert.rejects(first);await second;assert.deepEqual(order,[1,2]);assert.equal(JSON.parse(await readFile(f,'utf8')).version,2);}finally{await rm(dir,{recursive:true});}});
const record=(id,extra={})=>({schema:1,id,name:'A · v1',description:'',kind:'standard',createdAt:'2026-09-26',dshVersion:'0.1.7-rc.2',origin:'published',plugins:[{id:'skill-filesystem',name:'@deepseek-ai/dsh-skill-filesystem',config:{customSkillDirs:[]}}],skillRoots:[],...extra});
test('stored versions are immutable, account-relative and discardable',async()=>{const dir=await mkdtemp(join(tmpdir(),'workbench-presets-'));try{const store=presetStore(dir);const id='wb-1-0000abcd';await store.save(record(id,{skillRoots:['skills/wb-1-0000abcd/check']}));await assert.rejects(()=>store.save(record(id)),/EEXIST/);assert.deepEqual((await store.list()).map(r=>r.id),[id]);assert.deepEqual(store.definition((await store.list())[0]).plugins[0].config.customSkillDirs,[join(dir,'skills/wb-1-0000abcd/check')]);await assert.rejects(()=>store.save(record('wb-2-0000abcd',{skillRoots:['../escape']})));await assert.rejects(()=>store.save(record('../escape')));await store.discard(id);assert.deepEqual(await store.list(),[]);}finally{await rm(dir,{recursive:true});}});
test('alpha.5 directories convert once, keep ids, move frozen Skills and follow the installed creator skills',async()=>{const home=await mkdtemp(join(tmpdir(),'workbench-legacy-'));try{const data=join(home,'workbench'),store=presetStore(data);const id='wb-1790150116945-673bdb6e',dir=join(home,'.agent-presets',id),skill=join(dir,'workbench-skills','check');await mkdir(join(skill,'check'),{recursive:true});await writeFile(join(skill,'check','SKILL.md'),'---\nname: check\ndescription: d\n---\n');await writeFile(join(dir,'preset.yml'),'name: 验证 A · v1\ndescription: 固定版本\n');await writeFile(join(dir,'agent.cordis.yml'),`- id: tool-bash\n  name: '@deepseek-ai/dsh-tool-bash'\n  disabled: !!js process.platform === 'win32'\n- id: skill-filesystem\n  name: '@deepseek-ai/dsh-skill-filesystem'\n  config:\n    customSkillDirs:\n      - ${skill}\n      - !!js "process.getBuiltinModule('node:url').fileURLToPath(new URL('skills/', baseUrl))"\n      - /elsewhere\n`);await mkdir(join(home,'.agent-presets','standard-copy'),{recursive:true});const alpha1=join(home,'.agent-presets','wb-1789887885646-b1be67');await mkdir(alpha1,{recursive:true});await writeFile(join(alpha1,'agent.cordis.yml'),"- id: persona\n  name: '@deepseek-ai/dsh-persona'\n");
 const creator=[{__jsExpr:"require('@deepseek-ai/dsh-agent-preset/package.json')"}];
 assert.deepEqual(await migrateLegacyDirectories({home,data,store,creatorSkillDirs:creator,dshVersion:'0.1.7-rc.2'}),['wb-1789887885646-b1be67',id]);assert.deepEqual(await migrateLegacyDirectories({home,data,store,creatorSkillDirs:creator,dshVersion:'0.1.7-rc.2'}),[]);
 const saved=(await store.list()).find(r=>r.id===id);assert.equal((await store.list()).length,2);assert.equal(saved.id,id);assert.equal(saved.name,'验证 A · v1');assert.equal(saved.origin,'migrated-alpha5');assert.deepEqual(saved.plugins[0].disabled,{__jsExpr:"process.platform === 'win32'"});assert.deepEqual(saved.plugins[1].config.customSkillDirs,[...creator,'/elsewhere']);assert.deepEqual(saved.skillRoots,[`skills/${id}/check`]);assert.deepEqual(await readdir(join(data,'skills',id,'check')),['check']);assert.deepEqual(await readdir(join(home,'.agent-presets',id,'workbench-skills','check')),['check']);
 }finally{await rm(home,{recursive:true});}});
