import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {parseDocument} from 'yaml';
import {Draft,defaults,composePreset} from '../plugin/config.mjs';
import {writeJson,readJson,serialQueue} from '../plugin/store.mjs';
import {migrate,assertRevision,adoptCandidate,ownsPreset} from '../plugin/modes.mjs';
import {observeSession} from '../plugin/host.mjs';
const source=kind=>readFile(`node_modules/@deepseek-ai/dsh-agent-presets/presets/${kind}/agent.cordis.yml`,'utf8');
const parse=text=>parseDocument(text,{customTags:[{tag:'tag:yaml.org,2002:js',resolve:v=>v}]}).contents.items;
test('all four bases preserve platform conditions, creator skills, persistent shell and presentation',async()=>{
 const standard=await source('standard');for(const kind of ['standard','ptc','minimal','cordis']){const draft=defaults(kind);draft.instructions='先给结论';const compiled=composePreset(await source(kind),draft,[],standard),rows=parse(compiled);assert(compiled.includes('先给结论'));if(kind==='minimal'){assert(rows.find(r=>r.get('id')==='persistent-shell'));assert.equal(rows.find(r=>r.get('id')==='persona').getIn(['config','complete']),true);}else{assert.equal(rows.find(r=>r.get('id')==='tool-pwsh').get('disabled',true).tag,'tag:yaml.org,2002:js');}if(kind==='cordis'){assert.equal(rows.find(r=>r.get('id')==='tool-plugin-manager').get('disabled'),false);assert.match(compiled,/new URL\('skills\//);}if(kind==='ptc')assert.equal(rows.find(r=>r.get('id')==='tool-presentation').getIn(['config','mode']),'ptc');}
});
test('minimal can add capabilities without replacing the persistent terminal',async()=>{const d=defaults('minimal');d.tools.files=true;d.presentation='ptc';const result=composePreset(await source('minimal'),d,['/snapshot/skill'],await source('standard'));assert.match(result,/persistent-shell/);assert.match(result,/tool-fs/);assert.match(result,/tool-skill/);assert.match(result,/tool-presentation/);assert.doesNotMatch(result,/- id: tool-bash\n/);});
test('disabled tool groups and MCP contribute only the selected capabilities',async()=>{const d=defaults();d.tools.files=false;d.tools.subagent=false;d.defaultSkills=false;d.mcp=[{id:'files',command:'/usr/bin/node',args:['server.mjs'],enabled:true},{id:'off',command:'node',args:[],enabled:false}];const text=composePreset(await source('standard'),d,[]),rows=parse(text);for(const id of ['tool-fs','tool-fs-search','delegation'])assert.equal(rows.find(r=>r.get('id')===id).get('disabled'),true);assert.match(text,/failOnStartupError: true/);assert.doesNotMatch(text,/workbench-mcp-off/);assert.equal(rows.find(r=>r.get('id')==='skill-filesystem').getIn(['config','includeDefaultRoots']),false);});
test('invalid fields, duplicate services, and evolution without observation are rejected',()=>{const d=defaults();const m={id:'same',command:'node',args:[],enabled:true};for(const patch of [{label:''},{mcp:[m,m]},{mcp:[{...m,id:'../escape'}]},{unexpected:true},{observe:false,evolution:{enabled:true,goal:''}},{instructions:'{{unknown}}'},{pluginManager:true}])assert.throws(()=>Draft.parse({...d,...patch}));});
test('legacy migration preserves preset identity and isolated drafts',()=>{const d={label:'旧配置',tools:defaults().tools,skills:[],mcp:[]};const old={schema:1,draft:d,versions:[{id:'old-v1',label:d.label,createdAt:'2026-09-01',config:d}],lastError:null};const migrated=migrate(old,'old-v1');assert.equal(migrated.modes.length,5);const legacy=migrated.modes[4];assert.equal(legacy.current,'old-v1');assert.equal(legacy.draft.defaultSkills,false);assert(ownsPreset(legacy,'old-v1'));legacy.draft.tools.files=false;assert(migrated.modes[0].draft.tools.files);assert.deepEqual(migrate(migrated,'old-v1'),migrated);assert.equal(old.draft.tools.files,true);assert.throws(()=>migrate({schema:99},'standard'));});
test('stale or unverified candidates cannot overwrite a draft',()=>{const mode=migrate(null,'standard').modes[0];mode.draft.evolution.enabled=true;mode.candidates=[{id:'c',status:'pending',basePreset:'standard',baseRevision:0,config:{...defaults(),instructions:'improve'},evidence:null}];assert.throws(()=>adoptCandidate(mode,'c'),/证据/);mode.candidates[0].evidence={baseline:'before',candidate:'after',sessionId:'s'};assertRevision(mode,0);mode.draftRevision=1;assert.throws(()=>adoptCandidate(mode,'c'),/草稿/);mode.draftRevision=0;mode.current='new';assert.throws(()=>adoptCandidate(mode,'c'),/基准/);mode.current='standard';adoptCandidate(mode,'c');assert.equal(mode.draft.instructions,'improve');assert.equal(mode.draftRevision,1);assert.throws(()=>adoptCandidate(mode,'c'),/已采用/);});
test('observation uses actual selected preset and request, not current defaults',()=>{assert.equal(observeSession({meta:{agentPreset:'standard'},events:[]}).model,null);const result=observeSession({meta:{agentPreset:'standard'},events:[{type:'agent-preset/selected',data:{agentPreset:'custom'}},{type:'request/header',data:{header:{config:{provider:'deepseek',model:'actual-model'}}}},{type:'tool/result',data:{message:{content:[]},error:{code:'bad'}}}]});assert.equal(result.presetId,'custom');assert.equal(result.model,'actual-model');assert.equal(result.toolErrors,1);});
test('atomic records and serialized failures retain the next operation',async()=>{const dir=await mkdtemp(join(tmpdir(),'workbench-store-'));try{const f=join(dir,'state.json');await writeJson(f,{version:1});assert.deepEqual(await readJson(f,null),{version:1});const queue=serialQueue();const order=[];const first=queue(async()=>{order.push(1);throw Error('rejected');});const second=queue(async()=>{order.push(2);await writeJson(f,{version:2});});await assert.rejects(first);await second;assert.deepEqual(order,[1,2]);assert.equal(JSON.parse(await readFile(f,'utf8')).version,2);}finally{await rm(dir,{recursive:true});}});

test('creator inspection leases survive one scope disposal and unwind partial registration',async()=>{
 const {acquireInspectProviders}=await import('../plugin/inspect-leases.mjs');const root={},live=new Set();
 const register=id=>{assert(!live.has(id));live.add(id);return()=>live.delete(id);};
 const first=acquireInspectProviders(root,()=>['Service','Tool'],register),second=acquireInspectProviders(root,()=>['Service','Tool'],register);
 assert.equal(live.size,2);first();first();assert.equal(live.size,2);second();assert.equal(live.size,0);
 assert.throws(()=>acquireInspectProviders(root,()=>['Service','broken'],id=>{if(id==='broken')throw Error('registration failed');return register(id);}),/registration failed/);assert.equal(live.size,0);
 const third=acquireInspectProviders(root,()=>['Service','Tool'],register);assert.equal(live.size,2);third();assert.equal(live.size,0);
});
