import React,{useState} from 'react';
import {Glyph,ColorIcon,Button,Empty,Field,Modal,DocText} from './App.jsx';
import {makeId} from './data.js';

function Heading({eyebrow,title,description,children}){return <header className="module-heading"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div>{children}</header>;}
function Tabs({items,value,onChange}){return <div className="tabs" role="tablist">{items.map(x=><button role="tab" aria-selected={value===x} key={x} className={value===x?'active':''} onClick={()=>onChange(x)}>{x}</button>)}</div>;}

export function Capabilities({account,update,notify}){
 const [tab,setTab]=useState('全部'),[search,setSearch]=useState(''),[edit,setEdit]=useState(null),[importing,setImporting]=useState(false),[checked,setChecked]=useState(false);
 const list=account.capabilities.filter(c=>(tab==='全部'||c.type===tab)&&(`${c.name}${c.description}`).includes(search));
 const toggle=id=>update(a=>({...a,capabilities:a.capabilities.map(c=>c.id===id?{...c,enabled:!c.enabled}:c)}));
 return <section data-feature="CAP-01"><Heading eyebrow="CAPABILITIES" title="能力广场" description="把做事的方法、可用的工具和专业伙伴，装进你的工作台。"><Button variant="primary" icon="Plus" onClick={()=>setImporting(true)}>添加能力</Button></Heading><div className="module-bar"><Tabs items={['全部','Skill','连接器','Subagent']} value={tab} onChange={setTab}/><label className="search-box"><Glyph name="MagnifyingGlass"/><input aria-label="搜索能力" placeholder="搜索能力" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="capability-grid">{list.map(c=><section key={c.id} className="capability-card"><div className="cap-card-top"><span className={`cap-icon ${c.type==='Subagent'?'purple':c.type==='连接器'?'blue':''}`}><Glyph name={c.icon} size={27}/></span><button role="switch" aria-checked={c.enabled} aria-label={`启用 ${c.name}`} className={`switch ${c.enabled?'on':''}`} onClick={()=>toggle(c.id)}><span/></button></div><button className="cap-title" onClick={()=>{setEdit(c);setChecked(false);}}><h3>{c.name}</h3><span>{c.type}</span></button><p>{c.description}</p><footer><span>{c.enabled?'已启用':'未启用'} · 本地演示</span><button onClick={()=>{setEdit(c);setChecked(false);}}>配置<Glyph name="ArrowUpRight" size={17}/></button></footer></section>)}</div>{!list.length&&<Empty title="没有匹配的能力" body="试试其他关键词或分类。"/>}<div className="module-note"><Glyph name="Info"/>这里展示配置体验。演示中的能力不会访问真实服务或执行工具。</div>
 {edit&&<Modal title={`配置 · ${edit.name}`} onClose={()=>setEdit(null)}><form onSubmit={e=>{e.preventDefault();update(a=>({...a,capabilities:a.capabilities.map(c=>c.id===edit.id?edit:c)}));setEdit(null);notify('配置已保存，后续演示任务使用新设置。');}}><Field label="名称"><input required value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></Field><Field label="作用范围"><select value={edit.scope} onChange={e=>setEdit({...edit,scope:e.target.value})}><option>当前工作空间</option><option>账号通用</option></select></Field><Field label={edit.type==='连接器'?'连接说明（示例）':'执行指令'}><textarea rows={4} value={edit.instructions} onChange={e=>setEdit({...edit,instructions:e.target.value})}/></Field><div className="callout"><Glyph name="ShieldCheck"/>仅模拟权限配置，不会授予真实目录或账号访问权限。</div>{checked&&<p className="success-line"><Glyph name="CheckCircle"/>演示检查通过：配置已填写，真实连接尚未建立。</p>}<footer><Button type="button" onClick={()=>setChecked(true)} icon="Plug">演示检查</Button><Button type="submit" variant="primary">保存配置</Button></footer></form></Modal>}
 {importing&&<Modal title="添加演示能力" onClose={()=>setImporting(false)}><p className="muted">填写能力信息，预演本地导入流程。不读取文件或连接外部服务。</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);update(a=>({...a,capabilities:[...a.capabilities,{id:makeId(),name:f.get('name'),type:f.get('type'),description:f.get('description')||'你添加的演示能力。',icon:'PuzzlePiece',enabled:false,scope:'当前工作空间',instructions:'待补充执行说明。'}]}));setImporting(false);notify('已添加，配置并启用后可用于新任务。');}}><Field label="能力类型"><select name="type"><option>Skill</option><option>连接器</option><option>Subagent</option></select></Field><Field label="名称"><input required name="name" placeholder="例如：周报整理"/></Field><Field label="能力说明"><textarea name="description" rows={3}/></Field><footer><Button variant="primary" type="submit">添加到能力广场</Button></footer></form></Modal>}
 </section>;
}

export function Harness({account,update,notify}){
 const [selected,setSelected]=useState('上下文'),[edit,setEdit]=useState(false),[feedback,setFeedback]=useState(false),[reason,setReason]=useState('结果缺少项目背景'),[proposal,setProposal]=useState(false),[trial,setTrial]=useState(false),[history,setHistory]=useState(false);
 const h=account.harness;
 const modules=[['模型','Cpu','DeepSeek'],['上下文','Stack',h.context],['能力','Wrench',`${account.capabilities.filter(c=>c.enabled).length} 项启用`],['权限','ShieldCheck','按任务授权'],['会话','ClockCounterClockwise','保留过程与结果']];
 const selectedModule=modules.find(m=>m[0]===selected);
 const commit=(context,note)=>update(a=>{const version=`v${a.harness.history.length+1}`;return {...a,harness:{...a.harness,version,context,history:[...a.harness.history,{version,context,note}]}};});
 return <section><Heading eyebrow="HARNESS" title="你的执行方式" description="看清 Agent 如何工作，让每次改进都有依据、可以回退。"><Button icon="ClockCounterClockwise" onClick={()=>setHistory(true)}>配置版本 · {h.version}</Button></Heading><div className="harness-status"><span className="status complete">演示配置</span><span>个人工作台</span><span>最后更新：本地</span></div><section className="flow-section" data-feature="HARNESS-01"><div className="section-heading"><h2>任务如何被完成</h2><span className="muted">选择模块查看配置</span></div><div className="flow">{modules.map(([title,icon,value],i)=><React.Fragment key={title}><button className={`flow-node ${selected===title?'active':''}`} onClick={()=>setSelected(title)}><Glyph name={icon} size={30}/><strong>{title}</strong><span>{value}</span></button>{i<modules.length-1&&<Glyph name="ArrowRight" className="flow-arrow" size={19}/>}</React.Fragment>)}</div></section><div className="harness-lower"><section className="settings-panel"><div className="section-heading"><h2>{selected}设置</h2>{selected==='上下文'&&<Button icon="SlidersHorizontal" onClick={()=>setEdit(true)}>编辑</Button>}</div><dl><div><dt>当前选择</dt><dd>{selectedModule[2]}</dd></div><div><dt>配置来源</dt><dd>本地账号 / {h.version}</dd></div><div><dt>生效方式</dt><dd>从下一次任务开始</dd></div></dl><p className="muted">{selected==='上下文'?'先使用工作空间知识，再按需要补充账号通用知识。':selected==='权限'?'每次操作都在明确的授权范围内进行。':selected==='会话'?'任务输入、工具过程与成果关联保留。':'实际接入后，这里将展示 DSH 生效的配置。'}</p></section><section className="improve-panel" data-feature="HARNESS-02"><Glyph name="Sparkle" size={27}/><h2>从一项真实工作开始改进</h2><p>反馈结果中的问题，查看建议，再用相同任务比较两种配置。</p><Button variant="primary" icon="SlidersHorizontal" onClick={()=>setFeedback(true)}>改进执行方式</Button><small>当前 A/B 流程与结果均为演示样例。</small></section></div>
 {edit&&<Modal title={`编辑${selected}配置`} onClose={()=>setEdit(false)}><p className="muted">Demo 可调整上下文策略；其余模块展示配置，正式可编辑字段由 DSH 接入验证确定。</p><form onSubmit={e=>{e.preventDefault();commit(new FormData(e.currentTarget).get('context'),'手动调整上下文策略');setEdit(false);notify('已保存新的演示配置版本。');}}><Field label="上下文策略"><select name="context" defaultValue={h.context}><option>项目优先</option><option>按需检索</option><option>显式引用</option></select></Field><footer><Button variant="primary" type="submit">保存为新版本</Button></footer></form></Modal>}
 {feedback&&<Modal title="这次任务哪里可以更好？" onClose={()=>setFeedback(false)}><Field label="任务反馈"><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4}/></Field><p className="muted">关联任务：{account.task?.prompt||'整理产品方案与下一步行动'}</p><footer><Button variant="primary" disabled={!reason.trim()} onClick={()=>{setFeedback(false);setProposal(true);setTrial(false);}}>查看改进建议</Button></footer></Modal>}
 {proposal&&<Modal title="改进建议 · 上下文检索" onClose={()=>setProposal(false)} wide><p>针对“{reason}”，建议在回答前增加一次按需知识检索。</p><div className="compare-grid"><section><span className="eyebrow">当前 · {h.version}</span><h3>{h.context}</h3><p>使用工作空间默认上下文。</p></section><section><span className="eyebrow">建议配置</span><h3>按需检索</h3><p>检索相关 Wiki，附带来源，再整理结论。</p></section></div>{trial?<><table className="data-table"><caption>示例 A/B 结果 · 非真实测量</caption><thead><tr><th>固定任务</th><th>当前配置</th><th>建议配置</th></tr></thead><tbody><tr><td>整理产品方案</td><td>2 处待补依据</td><td>引用来源完整</td></tr><tr><td>回顾项目决策</td><td>遗漏 1 条</td><td>覆盖全部样例</td></tr><tr><td>生成行动清单</td><td>可用</td><td>可用</td></tr></tbody></table><p className="muted">实际工程将使用相同输入、模型及评分规则记录真实结果。</p></>:<div className="callout">建议不会自动生效。先查看固定样例的对比过程，再决定是否应用。</div>}<footer><Button onClick={()=>setTrial(true)} icon="Play">{trial?'重新查看示例':'演示 A/B 试跑'}</Button><Button variant="primary" disabled={!trial} onClick={()=>{commit('按需检索',`任务反馈：${reason}`);setProposal(false);notify('已应用新版本，可在配置版本中回退。');}}>应用建议版本</Button></footer></Modal>}
 {history&&<Modal title="配置版本" onClose={()=>setHistory(false)}>{[...h.history].reverse().map(v=><div className="version-row" key={v.version}><div><strong>{v.version} {v.version===h.version&&<span className="status complete">当前</span>}</strong><p>{v.context} · {v.note}</p></div>{v.version!==h.version&&<Button onClick={()=>{update(a=>({...a,harness:{...a.harness,version:v.version,context:v.context}}));notify(`已回退到 ${v.version}，后续任务使用该版本。`);}}>恢复此版本</Button>}</div>)}</Modal>}
 </section>;
}

export function Knowledge({account,update,notify,openDoc}){
 const [tab,setTab]=useState('Wiki'),[query,setQuery]=useState(''),[importing,setImporting]=useState(false),[view,setView]=useState(null),[source,setSource]=useState(null);
 const activeSources=account.sources.filter(s=>s.status!=='已撤销');
 const list=account.wiki.filter(w=>(w.title+w.body).includes(query));
 const usable=account.wiki.filter(w=>w.status==='已收录'&&activeSources.some(s=>s.id===w.source));
 function approve(w){update(a=>({...a,wiki:a.wiki.map(x=>x.id===w.id?{...x,status:'已收录'}:x)}));setView(null);notify('知识已收录，可用于后续演示检索。');}
 function revoke(s){update(a=>({...a,sources:a.sources.map(x=>x.id===s.id?{...x,status:'已撤销'}:x),wiki:a.wiki.map(w=>w.source===s.id?{...w,status:'来源已撤销'}:w)}));setSource(null);notify('已撤销来源，相关知识与关系退出可用范围。');}
 return <section><Heading eyebrow="KNOWLEDGE" title="让知识留下来" description="从你的资料和对话中积累，带着来源，回到下一次工作。"><Button variant="primary" icon="Plus" onClick={()=>setImporting(true)}>导入资料</Button></Heading><div className="knowledge-scope"><Glyph name="Folder" size={18}/><strong>个人工作台</strong><span>项目知识</span><span className="scope-spacer"/>{usable.length} 条可用知识 · {activeSources.length} 个来源</div><div className="module-bar"><Tabs items={['Wiki','来源','图谱']} value={tab} onChange={setTab}/><label className="search-box"><Glyph name="MagnifyingGlass"/><input aria-label="搜索知识" placeholder="搜索知识与来源" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {tab==='Wiki'&&<div className="wiki-list" data-feature="KNOW-01">{list.map(w=><button className="wiki-row" key={w.id} onClick={()=>setView(w)}><span className="wiki-symbol"><Glyph name="BookOpen" size={26}/></span><div><h3>{w.title}</h3><p>{w.body}</p><small>来源：{account.sources.find(s=>s.id===w.source)?.name||'未知来源'} · 工作空间</small></div><span className={`status ${w.status==='已收录'?'complete':w.status==='待审阅'?'waiting':''}`}>{w.status}</span><Glyph name="CaretRight" size={18}/></button>)}{!list.length&&<Empty title="还没有相关知识" body="导入示例资料，看看知识是怎样积累的。"><Button onClick={()=>setImporting(true)}>导入资料</Button></Empty>}</div>}
 {tab==='来源'&&<section data-feature="KNOW-02"><div className="source-head"><span>名称</span><span>类型</span><span>状态</span></div>{account.sources.filter(s=>s.name.includes(query)).map(s=><button className="source-row" key={s.id} onClick={()=>setSource(s)}><span><Glyph name={s.kind==='会话'?'ChatCircleText':'FileText'} size={22}/>{s.name}</span><span>{s.kind}</span><span className="status">{s.status}</span></button>)}{!account.sources.length&&<Empty title="暂无来源" body="工作空间与本产品会话会从这里导入。"/>}</section>}
 {tab==='图谱'&&<section className="graph-section" data-feature="KNOW-02"><div className="graph-legend"><span>来源</span><Glyph name="ArrowRight"/><span>有依据的关系</span><Glyph name="ArrowRight"/><span>知识</span></div><div className="graph-board">{usable.filter(w=>(w.title+w.body).includes(query)).map(w=><div className="graph-relation" key={w.id}><button className="graph-node source-node" onClick={()=>setSource(account.sources.find(s=>s.id===w.source))}><Glyph name="FileText" size={25}/>{account.sources.find(s=>s.id===w.source)?.name}</button><button className="relation-edge" onClick={()=>setView(w)}><span>支持</span><Glyph name="ArrowRight" size={25}/><small>查看依据</small></button><button className="graph-node" onClick={()=>setView(w)}><Glyph name="BookOpen" size={25}/>{w.title}</button></div>)}</div>{!usable.length&&<Empty title="等待第一条已确认知识" body="审阅并收录 Wiki 后，来源关系会显示在这里。"/>}<p className="module-note">图谱只展示已审阅且来源有效的示例关系。点击节点或关系可追溯依据。</p></section>}
 {importing&&<Modal title="导入示例资料" onClose={()=>setImporting(false)}><p className="muted">选择示例来源，预览“导入 → 候选知识 → 审阅”的流程。不会读取本机文件。</p><form onSubmit={e=>{e.preventDefault();const names=new FormData(e.currentTarget).getAll('sources');if(!names.length)return notify('至少选择一个示例来源。');update(a=>{const next=names.map(name=>({id:makeId(),name,kind:name.includes('会话')?'会话':'工作空间',status:'已索引',snippet:'产品方案承载完整内容，Demo 对齐主要交互，二者确认后再启动正式工程。'}));return {...a,sources:[...a.sources,...next],wiki:[...a.wiki,...next.map(s=>({id:makeId(),title:`${s.name} · 关键结论`,body:s.snippet,status:'待审阅',source:s.id}))]};});setImporting(false);setTab('Wiki');notify('示例导入完成，候选知识等待你的审阅。');}}>{['项目背景.md','产品规划会话','当前任务会话'].map((name,i)=><label className="check-row" key={name}><input type="checkbox" name="sources" value={name} defaultChecked={i===0}/><span><strong>{name}</strong><small>预置样例 · 不读取真实文件</small></span></label>)}<div className="callout">示例片段：产品方案定义完整内容，Demo 用来对齐样式与关键交互。</div><footer><Button variant="primary" type="submit">生成候选知识</Button></footer></form></Modal>}
 {view&&<Modal title={view.title} onClose={()=>setView(null)} wide><span className="status">{view.status}</span><div className="wiki-editor"><h3>整理后的内容</h3><p>{view.body}</p></div><div className="citation"><span className="eyebrow">来源依据</span><button onClick={()=>{setSource(account.sources.find(s=>s.id===view.source));setView(null);}}><Glyph name="FileText"/>{account.sources.find(s=>s.id===view.source)?.name}<Glyph name="ArrowUpRight" size={16}/></button><blockquote>{account.sources.find(s=>s.id===view.source)?.snippet}</blockquote></div><footer><Button onClick={()=>{openDoc(view.title,`# ${view.title}\n\n${view.body}\n\n来源：${account.sources.find(s=>s.id===view.source)?.name}`);setView(null);}}>查看正文</Button>{view.status==='待审阅'&&<><Button onClick={()=>{update(a=>({...a,wiki:a.wiki.filter(w=>w.id!==view.id)}));setView(null);notify('已丢弃候选知识，原始来源仍保留。');}}>丢弃</Button><Button variant="primary" onClick={()=>approve(view)}>确认收录</Button></>}</footer></Modal>}
 {source&&<Modal title={`来源 · ${source.name}`} onClose={()=>setSource(null)}><dl><div><dt>来源类型</dt><dd>{source.kind}</dd></div><div><dt>状态</dt><dd>{source.status}</dd></div><div><dt>范围</dt><dd>当前账号 / 个人工作台</dd></div></dl><blockquote>{source.snippet}</blockquote><small className="muted">以上为演示片段；正式工程将支持定位原文件或会话事件。</small><footer>{source.status!=='已撤销'&&<Button onClick={()=>revoke(source)} icon="LinkBreak">撤销来源</Button>}<Button variant="primary" onClick={()=>setSource(null)}>完成</Button></footer></Modal>}
 </section>;
}

export function Collaboration({account,update,notify}){
 const [newContact,setNewContact]=useState(false),[compose,setCompose]=useState(false),[draft,setDraft]=useState(null);
 return <section data-feature="COLLAB-01"><Heading eyebrow="COLLABORATION" title="让 Agent 一起工作" description="定义你的伙伴与共享范围，从一份清楚的委派开始。"><Button variant="primary" icon="Plus" onClick={()=>setCompose(true)}>创建协作草稿</Button></Heading><div className="collaboration-intro"><span className="agent-avatar"><Glyph name="Robot" size={38}/></span><div><span className="eyebrow">我的 Agent</span><h2>{account.name}的工作伙伴</h2><p>资料整理、方案写作与知识积累</p></div><span className="status">本地身份 · 尚未联网</span></div><div className="section-heading"><h2>协作对象</h2><Button icon="UserPlus" onClick={()=>setNewContact(true)}>添加对象</Button></div><div className="contacts">{account.contacts.map(c=><div key={c.id} className="contact"><span className="avatar"><Glyph name="User"/></span><div><strong>{c.name}</strong><p>{c.role}</p></div><small>仅本地记录</small></div>)}</div>{!account.contacts.length&&<Empty title="还没有协作对象" body="添加一个示例联系人，定义未来如何一起工作。"/>}<section className="draft-section"><h2>协作草稿</h2>{account.drafts.length?account.drafts.map(d=><button className="draft-row" key={d.id} onClick={()=>setDraft(d)}><Glyph name="EnvelopeSimple" size={24}/><div><strong>{d.title}</strong><p>{d.to} · {d.materials.length} 份共享材料</p></div><span className="status">未发送</span><Glyph name="CaretRight"/></button>):<div className="draft-empty"><Glyph name="EnvelopeSimple" size={28}/><p>写清任务与交付结果，再决定共享什么。</p></div>}</section><div className="module-note"><Glyph name="Info"/>当前仅保存本地草稿，不连接对方，也不会发送消息。跨人通信仍待后续方案确认。</div>
 {newContact&&<Modal title="添加协作对象" onClose={()=>setNewContact(false)}><form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);update(a=>({...a,contacts:[...a.contacts,{id:makeId(),name:d.get('name'),role:d.get('role'),status:'仅本地记录'}]}));setNewContact(false);}}><Field label="名称"><input name="name" required placeholder="伙伴名称"/></Field><Field label="适合一起完成什么"><input name="role" required placeholder="例如：调研与方案审阅"/></Field><footer><Button variant="primary" type="submit">保存对象</Button></footer></form></Modal>}
 {compose&&<Modal title="创建协作草稿" onClose={()=>setCompose(false)}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);update(a=>({...a,drafts:[...a.drafts,{id:makeId(),title:f.get('title'),to:f.get('to'),description:f.get('description'),materials:f.getAll('materials')}]}));setCompose(false);notify('协作草稿已保存在本地，未发送任何消息。');}}><Field label="交给谁"><select name="to" required><option value="">选择协作对象</option>{account.contacts.map(c=><option key={c.id}>{c.name}</option>)}</select></Field>{!account.contacts.length&&<p className="muted">请先关闭此窗口并添加协作对象。</p>}<Field label="任务名称"><input name="title" required placeholder="例如：审阅个人工作台方案"/></Field><Field label="希望收到什么结果"><textarea name="description" required rows={3} placeholder="说明背景、要求和交付形式"/></Field><h3>明确共享范围</h3>{['产品方案.md','项目背景摘要'].map(x=><label className="check-row" key={x}><input type="checkbox" name="materials" value={x}/>{x}</label>)}<small className="muted">只共享所选内容，不默认开放全部知识或连接器。</small><footer><Button variant="primary" type="submit" disabled={!account.contacts.length}>保存草稿</Button></footer></form></Modal>}
 {draft&&<Modal title={draft.title} onClose={()=>setDraft(null)}><span className="status">本地草稿 · 未发送</span><h3>协作对象：{draft.to}</h3><p>{draft.description}</p><h3>共享材料</h3><p>{draft.materials.join('、')||'未选择材料'}</p><div className="callout">此 Demo 不提供外部发送。正式通信需在产品方案确认后实现。</div><footer><Button variant="primary" onClick={()=>setDraft(null)}>完成</Button></footer></Modal>}
 </section>;
}
