/** Real DSH profile checks in an isolated local account, with no paid model requests. */
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const url=new URL(await readFile('.local/test-url','utf8'));
const auth=await fetch(url,{redirect:'manual'}),cookie=auth.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');
async function call(action,payload={}){const response=await fetch(new URL(`/api/workbench/${action}`,url),{method:'POST',headers:{'content-type':'application/json',cookie},body:JSON.stringify(payload)});const r=await response.json();if(!r.ok)throw Error(r.error?.message);return r.value;}
const mode=(d,id)=>d.state.modes.find(m=>m.id===id);
const unauth=await fetch(new URL('/api/workbench/snapshot',url),{method:'POST',body:'{}'});assert.notEqual(unauth.status,200);
let state=await call('snapshot');assert.equal(state.state.schema,2);assert.equal(state.state.modes.filter(m=>m.builtin).length,4);
for(const id of ['standard','ptc','minimal','cordis']){const actual=await call('inspect',{modeId:id});assert(actual.inspection.tools.length>0);if(id==='minimal'){assert.equal(actual.inspection.tools.length,1);assert.equal(actual.inspection.tools[0].name,'bash');}if(id==='cordis')assert(actual.inspection.tools.some(t=>t.name.includes('plugin')));console.log(`PASS real builtin ${id} load (${actual.inspection.tools.length} tools)`);}
const path=resolve('.local/fixture-skill');await mkdir(path,{recursive:true});await writeFile(`${path}/SKILL.md`,'---\nname: workbench-check\ndescription: Local integration fixture\n---\nReturn the phrase local-skill-ok.\n');
state=await call('create',{kind:'standard',label:'验证 A'});const a=state.selectedId;
state=await call('create',{kind:'minimal',label:'验证 B'});const b=state.selectedId;const originalDefault=state.activeId;
let m=mode(state,a);let draft={...m.draft,tools:{files:true,shell:false,web:false,subagent:false},defaultSkills:false,skills:[{id:'check',path,enabled:true}],mcp:[{id:'check',command:process.execPath,args:[resolve('tests/fixtures/mcp.mjs')],enabled:true}],evolution:{enabled:true,goal:'Improve results'}};
state=await call('saveDraft',{modeId:a,revision:m.draftRevision,draft});await assert.rejects(()=>call('saveDraft',{modeId:a,revision:m.draftRevision,draft}),/草稿/);
state=await call('publish',{modeId:a,revision:mode(state,a).draftRevision});const first=mode(state,a).current;assert.equal(state.activeId,originalDefault);assert(!state.inspection.tools.some(t=>['bash','web_search','subagent','workflow'].includes(t.name)));assert(state.inspection.tools.some(t=>t.name==='mcp__check__ping'));assert(state.inspection.skills.some(s=>s.name==='workbench-check'));const firstSession=state.inspection.sessionId;console.log('PASS A independent publish, real tools, frozen Skill and MCP discovery');
state=await call('saveDraft',{modeId:b,revision:mode(state,b).draftRevision,draft:{...mode(state,b).draft,tools:{files:true,shell:true,web:false,subagent:false},instructions:'Test only',presentation:'ptc'}});state=await call('publish',{modeId:b,revision:mode(state,b).draftRevision});assert(state.inspection.tools.some(t=>t.name==='bash'));assert(state.inspection.tools.some(t=>t.name.includes('read')));assert.equal(mode(state,a).current,first);assert.equal(state.activeId,originalDefault);console.log('PASS custom minimal adds files and PTC while preserving persistent shell');
const started=await call('start',{modeId:b});assert(started.generatedSessionId);console.log('PASS mode start creates an openable workspace session');
state=await call('setDefault',{modeId:b});const bPreset=mode(state,b).current;assert.equal(state.activeId,bPreset);
state=await call('saveDraft',{modeId:a,revision:mode(state,a).draftRevision,draft:{...draft,tools:{...draft.tools,shell:true}}});state=await call('publish',{modeId:a,revision:mode(state,a).draftRevision});assert.equal(state.activeId,bPreset);assert.notEqual(mode(state,a).current,first);let observed=await call('observe',{modeId:a,sessionId:firstSession});assert.equal(observed.observation.presetId,first);assert.equal(observed.observation.model,null);assert(observed.sessions.some(s=>s.sessionId===firstSession));console.log('PASS original session retained, selected session observation, no invented model request');
state=await call('restore',{modeId:a,revision:mode(state,a).draftRevision,presetId:first,reason:'集成验证恢复'});assert.equal(mode(state,a).current,first);assert.equal(state.activeId,bPreset);
state=await call('saveDraft',{modeId:a,revision:mode(state,a).draftRevision,draft:{...draft,skills:[{id:'missing',path:'/nonexistent-workbench-skill',enabled:true}]}});await assert.rejects(()=>call('publish',{modeId:a,revision:mode(state,a).draftRevision}),/ENOENT/);state=await call('snapshot');assert.equal(mode(state,a).current,first);assert.equal(state.activeId,bPreset);state=await call('saveDraft',{modeId:a,revision:mode(state,a).draftRevision,draft});console.log('PASS failed publish preserves version and default');
state=await call('saveDraft',{modeId:a,revision:mode(state,a).draftRevision,draft:{...draft,mcp:[{id:'broken',command:'/nonexistent-workbench-mcp-program',args:[],enabled:true}]}});await assert.rejects(()=>call('publish',{modeId:a,revision:mode(state,a).draftRevision}));state=await call('snapshot');assert.equal(mode(state,a).current,first);assert.equal(state.activeId,bPreset);state=await call('saveDraft',{modeId:a,revision:mode(state,a).draftRevision,draft});console.log('PASS MCP startup failure preserves published mode and default');
for(const builtin of ['ptc','cordis']){const base=mode(state,builtin);state=await call('saveDraft',{modeId:builtin,revision:base.draftRevision,draft:{...base.draft,instructions:'Local check',pluginManager:false,presentation:'native'}});state=await call('publish',{modeId:builtin,revision:mode(state,builtin).draftRevision});assert.notEqual(mode(state,builtin).current,builtin);if(builtin==='cordis')assert(state.inspection.skills.some(x=>x.name==='cordis-plugin-development'),'creator skills resolve from the application install');assert.equal(state.activeId,bPreset);state=await call('restore',{modeId:builtin,revision:mode(state,builtin).draftRevision,presetId:builtin,reason:'Verify original restoration'});assert.equal(mode(state,builtin).current,builtin);if(builtin==='cordis')assert(state.inspection.tools.some(t=>t.name.includes('plugin')));}console.log('PASS PTC and creator customization plus original restoration');
state=await call('feedback',{modeId:a,sessionId:firstSession,text:'输出需要更清晰'});state=await call('candidate',{modeId:a,revision:mode(state,a).draftRevision,feedbackId:mode(state,a).feedback[0].id,config:{...draft,instructions:'先给结论'}});const c=mode(state,a).candidates[0];await assert.rejects(()=>call('adopt',{modeId:a,candidateId:c.id}),/证据/);state=await call('trial',{modeId:a,candidateId:c.id});const trial=state.generatedSessionId;assert(trial);assert.equal(mode(state,a).current,first);await assert.rejects(()=>call('evidence',{modeId:a,candidateId:c.id,baseline:'before',candidate:'after',sessionId:trial}),/没有模型回复/);console.log('PASS feedback, isolated candidate trial, evidence required and no automatic adoption');
await assert.rejects(()=>call('archive',{modeId:b,archived:true}),/默认/);state=await call('archive',{modeId:a,archived:true});assert(mode(state,a).archived);await assert.rejects(()=>call('start',{modeId:a}),/恢复/);await call('archive',{modeId:a,archived:false});console.log('PASS archive guards and authenticated RPC');
await writeFile('.local/verified-modes.json',JSON.stringify({a,b,first,bPreset}),{mode:0o600});
