/** Mode-centric management UI hosted by the official DSH Web client. */
import React,{useEffect,useRef,useState} from 'react';
import type {Draft,Mode,Snapshot,RPC} from './types';
import css from './style.css';
type Open=(sessionId:string)=>void;
type Ctx={effect:(f:()=>unknown,label:string)=>void;uiWorkspace:{openSession:Open};slots:{inject:(name:string,f:()=>unknown)=>void;register:(spec:Record<string,unknown>,component:React.ComponentType<any>)=>unknown}}; // Official slots accept heterogeneous component props; product data uses explicit types.
export const inject=['slots','connection','uiWorkspace'];
const viewMemory={modeId:'',tab:'edit',candidateId:''};
const editorCache=new Map<string,{draft:Draft;revision:number}>();
export function apply(ctx:Ctx){
 const style=document.createElement('style');style.textContent=css;document.head.append(style);ctx.effect(()=>()=>style.remove(),'workbench styles');
 const call:RPC=async(action,payload={})=>{const r=await(await fetch(`/api/workbench/${action}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)})).json();if(!r.ok)throw Error(r.error?.message??'操作失败');return r.value;};
 ctx.slots.inject('main',()=>ctx.slots.register({name:'main',key:'workbench-harness',inject:()=>({call,open:(id:string)=>ctx.uiWorkspace.openSession(id)})},Harness));
 ctx.slots.inject('sidebar.panellist',()=>ctx.slots.register({name:'sidebar.panellist',id:'workbench-harness',order:-10,label:()=>'Harness'},()=> <span style={{fontSize:18}}>◈</span>));
 ctx.slots.inject('sidebar.brand.name',()=>ctx.slots.register({name:'sidebar.brand.name'},()=> <strong className="fw-brand">Focus Workspace</strong>));
 for(const name of ['conversation.hero.brand.mark','sidebar.brand.mark'])ctx.slots.inject(name,()=>ctx.slots.register({name},()=> <span aria-hidden="true" style={{color:'#4b7461',fontSize:25}}>◈</span>));
}
function Harness({call,open}:{call:RPC;open:Open}){
 const [data,setData]=useState<Snapshot>();const [selected,setSelected]=useState(viewMemory.modeId||'standard');const [draft,setDraft]=useState<Draft>();const [dirty,setDirty]=useState(false);const [tab,setTab]=useState(viewMemory.tab);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [notice,setNotice]=useState('');const [newMode,setNewMode]=useState(false);const [newKind,setNewKind]=useState('standard');const [newName,setNewName]=useState('');const [showArchived,setShowArchived]=useState(false);const [jsonEditing,setJsonEditing]=useState(false);const [json,setJson]=useState('');const [sessionId,setSessionId]=useState('');const [feedback,setFeedback]=useState('');const [feedbackId,setFeedbackId]=useState('');const [candidateJson,setCandidateJson]=useState('');const [candidateId,setCandidateId]=useState(viewMemory.candidateId);const [baseline,setBaseline]=useState('');const [result,setResult]=useState('');const [proof,setProof]=useState('');const [restoreId,setRestoreId]=useState('');const [reason,setReason]=useState('');
 const editingRevision=useRef(0);
 const mode=data?.state.modes.find(m=>m.id===selected);const dirtyRef=useRef(false);dirtyRef.current=dirty||jsonEditing;
 useEffect(()=>{void call('snapshot').then(d=>{setData(d);const first=d.state.modes.find(m=>m.id===viewMemory.modeId&&!m.archived)??d.state.modes.find(m=>m.current===d.activeId)??d.state.modes[0];setSelected(first.id);viewMemory.modeId=first.id;const cached=editorCache.get(first.id);setDraft(cached?.draft??first.draft);setDirty(!!cached);editingRevision.current=cached?.revision??first.draftRevision;if(cached&&cached.revision!==first.draftRevision)setError('离开期间草稿已更新；请先读取最新草稿，避免覆盖。');}).catch(e=>setError(String(e)));},[]);
 useEffect(()=>{if(!mode?.draft.observe||!['observe','evolve'].includes(tab))return;let active=true;void call('observe',{modeId:selected}).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(String(e));});return()=>{active=false;};},[selected,tab,!!mode]);
 useEffect(()=>{if(dirty&&draft&&mode)editorCache.set(selected,{draft,revision:editingRevision.current});},[draft,dirty]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirtyRef.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
 function clearAux(){setSessionId('');setFeedbackId('');setCandidateId('');setCandidateJson('');setBaseline('');setResult('');setProof('');setRestoreId('');setReason('');setError('');setNotice('');setJsonEditing(false);}
 function select(m:Mode){if(dirtyRef.current&&!confirm('放弃当前未保存编辑？'))return;editorCache.delete(selected);const cached=editorCache.get(m.id);setSelected(m.id);viewMemory.modeId=m.id;viewMemory.candidateId='';setDraft(cached?.draft??m.draft);setDirty(!!cached);editingRevision.current=cached?.revision??m.draftRevision;clearAux();setData(d=>d?{...d,inspection:undefined,inventory:undefined,sessions:undefined,observation:undefined,changes:undefined}:d);}
 function change(next:Draft){setDraft(next);setDirty(true);setNotice('');}
 async function act(name:string,payload:Record<string,unknown>={},sync=false){if(!mode&&name!=='snapshot')return;setBusy(name);setError('');setNotice('');try{const d=await call(name,{...(name==='snapshot'||name==='create'?{}:{modeId:selected}),...payload});setData(previous=>d.selectedId?d:{...d,sessions:d.sessions??previous?.sessions,sessionTotal:d.sessionTotal??previous?.sessionTotal});const id=d.selectedId??selected;if(sync||d.selectedId){const m=d.state.modes.find(x=>x.id===id);if(m){editorCache.delete(id);setSelected(id);viewMemory.modeId=id;setDraft(m.draft);setDirty(false);editingRevision.current=m.draftRevision;setJsonEditing(false);}}setNotice(({saveDraft:'草稿已保存，尚未发布。',publish:'版本已通过加载检查并发布。已有对话保留原版本。',setDefault:'已设为未来新对话的默认模式。',restore:'已恢复该版本，已有对话保持不变。',candidate:'候选已保存，记录对照验证后才能采用。',adopt:'已采用到草稿；请检查差异并发布。',evidence:'已记录人工验证证据。',generate:'已提交真实模型任务，生成结果请在对话中查看。',feedback:'反馈已关联来源会话。'} as Record<string,string>)[name]??'已更新。');if(d.generatedSessionId)open(d.generatedSessionId);if(name==='create'){setNewMode(false);setNewName('');clearAux();}return d;}catch(e){setError(String(e).replace(/^Error: /,''));}finally{setBusy('');}}
 if(!data||!draft||!mode)return <div className="wb"><h1>Harness</h1><p role="alert">{error||'正在读取模式…'}</p><button onClick={()=>location.reload()}>重新加载</button></div>;
 const locked=!!busy;const unsaved=dirty||jsonEditing;const selectedCandidate=mode.candidates.find(c=>c.id===candidateId);const inspection=data.inspection?.presetId===mode.current?data.inspection:undefined;
 return <div className="wb">
  <header className="wb-head"><div><div className="wb-eyebrow">FOCUS WORKSPACE / HARNESS</div><h1>我的模式</h1><p>从四种 DSH 装配出发，让 Agent 适合你的工作。</p></div><span className="wb-local"><i/>{data.account.name}</span></header>
  <div className="wb-section"><div className="wb-actions"><span className="wb-pill">DSH {data.dshVersion}</span><label><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/> 显示归档</label></div><button className="primary" disabled={locked} onClick={()=>setNewMode(!newMode)}>＋ 新建模式</button></div>
  {newMode&&<section className="wb-card"><h2>新建模式</h2><div className="wb-formline"><label>DSH 类型<select value={newKind} onChange={e=>setNewKind(e.target.value)}>{data.kinds.map(k=><option key={k.id} value={k.id}>{k.label}</option>)}</select></label><label>名称<input aria-label="新模式名称" value={newName} onChange={e=>setNewName(e.target.value)} placeholder="例如：资料研究" maxLength={64}/></label><button disabled={locked||unsaved||!newName.trim()} onClick={()=>act('create',{kind:newKind,label:newName},true)}>创建独立草稿</button></div>{unsaved&&<p>先保存当前编辑，再创建模式。</p>}</section>}
  <div className="wb-mode-grid">{data.state.modes.filter(m=>!m.archived||showArchived).map(m=><button key={m.id} disabled={locked} className={`wb-mode ${selected===m.id?'selected':''}`} onClick={()=>select(m)}><span className="wb-section"><b>{m.draft.label}</b>{data.activeId===m.current&&<span className="wb-pill">默认</span>}</span><small>{data.kinds.find(k=>k.id===m.kind)?.label} · {m.builtin?(m.current===m.kind?'内置原版':'内置 · 已定制'):'自定义'}{m.archived?' · 已归档':''}</small><span className="wb-mode-status">{m.current?'已发布':'草稿'} · 观测{m.draft.observe?'开':'关'} · 进化{m.draft.evolution.enabled?'开':'关'}</span></button>)}</div>
  <div className="wb-toolbar"><div><strong>{draft.label}</strong><small className="wb-block">{data.kinds.find(k=>k.id===mode.kind)?.description}</small><code>{mode.current??'尚未发布'}</code></div><div className="wb-actions wrap"><button disabled={locked||unsaved} onClick={()=>{setNewMode(true);setNewName(`${draft.label} 副本`);setNewKind(mode.kind);}}>新增同类型</button><button disabled={locked||unsaved} onClick={()=>act('create',{kind:mode.kind,label:`${draft.label.slice(0,58)} 副本`,sourceId:mode.id},true)}>复制</button><button disabled={locked||!mode.current||mode.archived||mode.current===data.activeId||unsaved} onClick={()=>act('setDefault')}>设为默认</button><button className="primary" disabled={locked||unsaved||!mode.current||mode.archived} onClick={()=>act('start')}>以此模式开始对话</button></div></div>
  <nav className="wb-tabs">{[['edit','编辑模式'],['observe','运行观测'],['evolve','自进化'],['versions','版本与恢复']].map(([id,label])=><button key={id} disabled={locked} className={tab===id?'selected':''} onClick={()=>{setTab(id);viewMemory.tab=id;}}>{label}</button>)}</nav>
  {error&&<div className="wb-alert error" role="alert">{error}<button disabled={locked} onClick={()=>{if(!unsaved||confirm('放弃未保存编辑并读取最新草稿？'))void act('snapshot',{},true);}}>读取最新草稿</button></div>}{notice&&<div className="wb-alert" role="status">{notice}</div>}{busy&&<div className="wb-alert" role="status">正在处理，请稍候…</div>}{mode.lastError&&<div className="wb-alert error">最近发布失败：{mode.lastError}</div>}
  <fieldset className="wb-scope" disabled={locked||mode.archived}>
  {tab==='edit'&&<>
   <section className="wb-card"><div className="wb-section"><h2>基础配置</h2><button disabled={jsonEditing} onClick={()=>{setJson(JSON.stringify(draft,null,2));setJsonEditing(true);}}>高级 JSON 编辑</button></div><div className="wb-fields"><label>模式名称<input aria-label="模式名称" value={draft.label} onChange={e=>change({...draft,label:e.target.value})} maxLength={64}/></label><label>附加指令<textarea value={draft.instructions} onChange={e=>change({...draft,instructions:e.target.value})} placeholder="例如：先给结论，引用资料时附来源。" rows={4}/></label><label>工具呈现<select value={draft.presentation} onChange={e=>change({...draft,presentation:e.target.value as Draft['presentation']})}><option value="native">直接调用 · native</option><option value="ptc">程序化调用 · PTC</option></select></label></div><p className="wb-muted">模型在对话的模型选择器中配置。终端与权限保留 DSH 的审批规则；停用某类工具不等于撤销操作系统权限。</p>{mode.kind==='cordis'&&<label><input type="checkbox" checked={draft.pluginManager} onChange={e=>change({...draft,pluginManager:e.target.checked})}/> 允许创造模式使用 DSH 原生配置修改工具</label>}{draft.pluginManager&&<p className="wb-muted">原生工具可能修改 Host 或其他装配；这些修改不自动成为本页的模式版本，也不由本页回退。</p>}</section>
   {jsonEditing&&<section className="wb-card"><h2>编辑配置 JSON</h2><p className="wb-muted">与表单共用同一份配置。载入表单后，保存时由后端校验字段；不支持任意插件程序。</p><textarea aria-label="配置 JSON" className="wb-code" rows={20} value={json} onChange={e=>setJson(e.target.value)}/><div className="wb-actions"><button onClick={()=>{try{const p=JSON.parse(json);if(!p||typeof p!=='object'||Array.isArray(p))throw Error('需要 JSON 对象');void act('saveDraft',{revision:editingRevision.current,draft:p},true);}catch(e){setError(String(e));}}}>校验并保存 JSON 草稿</button><button onClick={()=>setJsonEditing(false)}>取消 JSON 编辑</button></div></section>}
   <section className="wb-card"><h2>工具装配</h2>{data.groups.map(g=><label className="wb-row" key={g.id}><span><b>{g.label}</b>{g.id==='shell'&&<small>{mode.kind==='minimal'?'持久终端':'独立命令执行'}</small>}</span><input type="checkbox" checked={draft.tools[g.id]} onChange={e=>change({...draft,tools:{...draft.tools,[g.id]:e.target.checked}})}/></label>)}{mode.kind==='minimal'&&<p className="wb-muted">极简添加其他工具后是自定义装配；原版依然可以恢复。Subagent 沿用所选模式的上游配置。</p>}</section>
   <Assets draft={draft} change={change}/>
   <section className="wb-card"><h2>观测与自进化属性</h2><label className="wb-row"><span>启用此模式的运行观测<small>关闭仅隐藏产品汇总；DSH 基础运行日志仍保留。</small></span><input type="checkbox" checked={draft.observe} onChange={e=>change({...draft,observe:e.target.checked,evolution:{...draft.evolution,enabled:e.target.checked&&draft.evolution.enabled}})}/></label><label className="wb-row"><span>启用受控自进化<small>反馈 → 候选 → 对照验证 → 人工采用 → 发布</small></span><input type="checkbox" checked={draft.evolution.enabled} onChange={e=>change({...draft,observe:e.target.checked||draft.observe,evolution:{...draft.evolution,enabled:e.target.checked}})}/></label><label>改进目标<textarea rows={2} value={draft.evolution.goal} onChange={e=>change({...draft,evolution:{...draft.evolution,goal:e.target.value}})} placeholder="例如：减少反复解释，输出可直接使用的研究结论。"/></label></section>
  </>}
  {tab==='observe'&&<>
   {!mode.draft.observe?<div className="wb-card">此模式的观测已关闭。在编辑模式中开启并保存。</div>:<><section className="wb-card"><div className="wb-section"><h2>已发布配置的实际装配</h2><button onClick={()=>act('observe')}>刷新会话列表</button><button disabled={!mode.current} onClick={()=>act('inspect')}>加载并检查</button></div><p className="wb-muted">这是发布版本的能力清单。检查不调用模型，加载启用的 MCP 时会启动对应程序。</p>{inspection&&<><div className="wb-stats"><div className="wb-stat"><small>可调用工具</small><strong>{inspection.tools.length}</strong></div><div className="wb-stat"><small>发现 Skills</small><strong>{inspection.skills.length}</strong></div></div><button onClick={()=>open(inspection.sessionId)}>打开检查会话</button>{inspection.tools.map(tool=><details className="wb-detail" key={tool.name}><summary>{tool.name}<span>{tool.source}</span></summary><p>{tool.description}</p></details>)}{inspection.skills.map(s=><div className="wb-row" key={s.name}><b>{s.name}</b><small>{s.description}</small></div>)}</>}{data.inventory?.agentPresets?.find(p=>p.id===mode.current)?.rows.map(e=><div className="wb-row" key={e.entryId}><div><b>{e.entryId}</b><small>{e.moduleName}</small></div><span className="wb-pill">{!e.enabled?'停用':e.fiberPhase??'未加载'}</span></div>)}</section><SessionList data={data} sessionId={sessionId} select={id=>{setSessionId(id);void act('observe',{sessionId:id});}} open={open}/>{data.observation&&<section className="wb-card"><h2>指定会话的真实记录</h2><code>{data.observation.sessionId} · {data.observation.presetId}</code><div className="wb-stats">{[['实际模型',data.observation.model??'尚未调用'],['工具结果',data.observation.toolCalls],['工具失败',data.observation.toolErrors],['事件数',data.observation.eventCount]].map(([k,v])=><div className="wb-stat" key={k}><small>{k}</small><b>{v}</b></div>)}</div><p>最近结束原因：{JSON.stringify(data.observation.lastOutcome)??'尚无结束记录'}</p></section>}</>}
  </>}
  {tab==='evolve'&&<>
   <section className="wb-card"><h2>让这个模式逐步改进</h2><p>目标：{mode.draft.evolution.goal||'尚未填写，可在编辑模式中定义。'}</p><span className="wb-pill">{mode.draft.evolution.enabled?'已开启 · 人工采用':'未开启'}</span><p className="wb-muted">生成建议会真实调用已配置模型。候选不会自动生效；验证记录由你确认，尚不提供自动评测或自动发布。</p></section>
   {mode.draft.evolution.enabled&&<><section className="wb-card"><h2>1. 记录来源反馈</h2><label>来源会话<select aria-label="反馈来源会话" value={sessionId} onChange={e=>setSessionId(e.target.value)}><option value="">选择此模式的真实会话</option>{data.sessions?.map(s=><option value={s.sessionId} key={s.sessionId}>{sessionTitle(s)} · {s.sessionId.slice(0,8)}</option>)}</select></label><textarea aria-label="任务反馈" value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="发生了什么，希望如何改善？" rows={3}/><button disabled={!sessionId||!feedback.trim()||unsaved} onClick={()=>act('feedback',{sessionId,text:feedback})}>保存反馈</button>{mode.feedback.map(f=><div className="wb-row" key={f.id}><div><strong>{f.text}</strong><small>来源：{f.sessionId}</small></div><div className="wb-actions"><button disabled={!mode.current||unsaved} onClick={()=>{if(confirm('使用当前配置的模型生成改进建议？只发送目标、所选反馈及此模式配置。'))void act('generate',{feedbackId:f.id});}}>生成改进任务</button>{f.taskSessionId&&<button onClick={()=>open(f.taskSessionId!)}>查看建议对话</button>}</div></div>)}</section>
   <section className="wb-card"><h2>2. 导入候选</h2><p className="wb-muted">将 Agent 回复的完整 JSON 粘贴在下方，也可以从当前配置手工调整。请选择候选对应的来源反馈。</p><select aria-label="候选来源反馈" value={feedbackId||mode.feedback[0]?.id||''} onChange={e=>setFeedbackId(e.target.value)}>{mode.feedback.map(f=><option key={f.id} value={f.id}>{f.text.slice(0,80)}</option>)}</select><button onClick={()=>setCandidateJson(JSON.stringify(draft,null,2))}>填入当前配置</button><textarea aria-label="候选 JSON" className="wb-code" value={candidateJson} onChange={e=>setCandidateJson(e.target.value)} rows={8} placeholder="完整配置 JSON"/><button disabled={!mode.feedback.length||!candidateJson||unsaved||!mode.current} onClick={()=>{try{void act('candidate',{revision:editingRevision.current,feedbackId:feedbackId||mode.feedback[0].id,config:JSON.parse(candidateJson)});}catch(e){setError(String(e));}}}>校验并保存候选</button></section>
   <section className="wb-card"><h2>3. 对照验证与采用</h2><p className="wb-muted">使用同一任务输入比较基准与候选，记录真实结果和证据会话。这里记录人工验证，不自动判定质量。</p><select aria-label="改进候选" value={candidateId} onChange={e=>{setCandidateId(e.target.value);viewMemory.candidateId=e.target.value;const c=mode.candidates.find(x=>x.id===e.target.value);setBaseline(c?.evidence?.baseline??'');setResult(c?.evidence?.candidate??'');setProof(c?.evidence?.sessionId??c?.trialSessionId??'');}}><option value="">选择候选</option>{mode.candidates.map(c=><option key={c.id} value={c.id}>{c.id.slice(0,8)} · {c.status==='adopted'?'已采用':'待验证'}</option>)}</select>{selectedCandidate&&<><button disabled={unsaved||selectedCandidate.status!=='pending'} onClick={()=>act('trial',{candidateId})}>打开候选试跑对话</button><p className="wb-muted">试跑会实际加载候选的工具与 MCP。在对话中输入与基准相同的任务，再回来记录结果。试跑不发布模式。</p><details><summary>查看完整候选配置</summary><pre className="wb-code">{JSON.stringify(selectedCandidate.config,null,2)}</pre></details><div className="wb-fields"><label>基准结果<textarea value={baseline} onChange={e=>setBaseline(e.target.value)} rows={2}/></label><label>候选结果<textarea value={result} onChange={e=>setResult(e.target.value)} rows={2}/></label><label>验证会话 ID<input value={proof} onChange={e=>setProof(e.target.value)} placeholder="真实存在的对照验证会话 ID"/></label></div><div className="wb-actions"><button disabled={selectedCandidate.status!=='pending'||!baseline.trim()||!result.trim()||(!proof.trim()&&!selectedCandidate.trialSessionId)} onClick={()=>act('evidence',{candidateId,baseline,candidate:result,sessionId:proof||selectedCandidate.trialSessionId})}>记录验证证据</button><button className="primary" disabled={unsaved||selectedCandidate.status!=='pending'||!selectedCandidate.evidence} onClick={()=>act('adopt',{candidateId},true)}>采用到模式草稿</button></div><p className="wb-muted">基准版本或草稿修订已变化时会拒绝采用；采用后需到编辑页发布。</p></>}</section></>}
  </>}
  {tab==='versions'&&<><section className="wb-card"><div className="wb-section"><h2>草稿与当前版本差异</h2><button disabled={unsaved} onClick={()=>act('diff')}>比较已保存草稿</button></div>{unsaved&&<p>请先保存修改再比较。</p>}{data.changes?.length===0&&<p>没有配置差异。</p>}{data.changes?.map(c=><details className="wb-detail" key={c.field}><summary>{c.field}</summary><p>之前：{JSON.stringify(c.before)}<br/>之后：{JSON.stringify(c.after)}</p></details>)}</section><section className="wb-card"><h2>不可变版本</h2><p className="wb-muted">恢复更新此模式的当前指针；账号默认若是此模式，将同步用于未来会话。已有会话不切换。</p>{mode.builtin&&<div className="wb-row"><strong>DSH 内置原版</strong><button disabled={unsaved||mode.current===mode.kind} onClick={()=>setRestoreId(mode.kind)}>恢复原版</button></div>}{mode.versions.map((v,i)=><div className="wb-row" key={v.id}><div><strong>{v.label} · v{mode.versions.length-i} {v.id===mode.current&&<span className="wb-pill">当前</span>}</strong><small>{new Date(v.createdAt).toLocaleString()} · {v.id}</small></div><button disabled={unsaved||v.id===mode.current} onClick={()=>setRestoreId(v.id)}>恢复此版本</button></div>)}{restoreId&&<div className="wb-fields"><code>恢复到 {restoreId}</code><label>恢复原因<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={!reason.trim()} onClick={()=>{void act('restore',{revision:editingRevision.current,presetId:restoreId,reason},true);setRestoreId('');}}>确认恢复</button></div>}</section><section className="wb-card"><h2>操作记录</h2>{data.state.audit.filter(a=>a.modeId===mode.id).slice(0,20).map((a,i)=><div className="wb-row" key={i}><strong>{a.action}</strong><small>{new Date(a.at).toLocaleString()} · {a.presetId}</small></div>)}</section></>}
  </fieldset>
  {mode.archived&&<div className="wb-alert">此模式已归档。<button disabled={locked} onClick={()=>act('archive',{archived:false},true)}>恢复归档</button></div>}
  {!mode.builtin&&!mode.archived&&tab==='versions'&&<button disabled={locked||unsaved||mode.current===data.activeId} onClick={()=>act('archive',{archived:true},true)}>归档模式</button>}
  {tab==='edit'&&!mode.archived&&<footer className="wb-save"><span>草稿修订 {mode.draftRevision} · {unsaved?'有未保存编辑':'已保存'}</span><button disabled={locked||!dirty||jsonEditing} onClick={()=>act('saveDraft',{revision:editingRevision.current,draft},true)}>保存草稿</button><button className="primary" disabled={locked||unsaved} onClick={()=>{if(confirm('将加载所选模式并启动已启用 MCP，检查成功后发布新版本。已有会话不变。'))void act('publish',{revision:editingRevision.current},true);}}>检查并发布</button></footer>}
 </div>;
}
function Assets({draft,change}:{draft:Draft;change:(d:Draft)=>void}){const [path,setPath]=useState('');const [name,setName]=useState('');const [command,setCommand]=useState('');const [args,setArgs]=useState('[]');const [error,setError]=useState('');return <>
 <section className="wb-card"><h2>Skills</h2><label><input type="checkbox" checked={draft.defaultSkills} onChange={e=>change({...draft,defaultSkills:e.target.checked})}/> 加载默认 Skill 目录和类型自带技能</label><p className="wb-muted">自带和默认目录按 DSH 规则读取；下方明确导入的 Skill 会在发布时复制为不可变快照。</p><div className="wb-formline"><input aria-label="Skill 目录" value={path} onChange={e=>setPath(e.target.value)} placeholder="含 SKILL.md 的绝对目录"/><button disabled={!path.trim()} onClick={()=>{change({...draft,skills:[...draft.skills,{id:`skill-${Date.now()}`,path:path.trim(),enabled:true}]});setPath('');}}>添加 Skill</button></div>{draft.skills.map((s,i)=><div className="wb-row" key={i}><span>{s.path}</span><div className="wb-actions"><label><input type="checkbox" checked={s.enabled} onChange={e=>change({...draft,skills:draft.skills.map((v,j)=>j===i?{...v,enabled:e.target.checked}:v)})}/>启用</label><button onClick={()=>change({...draft,skills:draft.skills.filter((_,j)=>i!==j)})}>移除</button></div></div>)}</section>
 <section className="wb-card"><h2>MCP · 本地 stdio</h2><p className="wb-muted">发布与装配检查会启动所填程序。这里仅填写服务配置，凭证仍由服务环境管理。</p><div className="wb-fields"><label>服务名称<input value={name} onChange={e=>setName(e.target.value)} placeholder="例如 local-files"/></label><label>程序<input value={command} onChange={e=>setCommand(e.target.value)} placeholder="命令或可执行文件绝对路径"/></label><label>参数 · JSON 数组<input value={args} onChange={e=>setArgs(e.target.value)}/></label></div><button onClick={()=>{try{const a:unknown=JSON.parse(args);if(!Array.isArray(a)||a.some(v=>typeof v!=='string'))throw Error('参数必须是字符串数组');if(!/^[A-Za-z0-9_-]{1,32}$/.test(name)||!command.trim())throw Error('填写合法名称与程序');if(draft.mcp.some(m=>m.id===name))throw Error('服务名重复');change({...draft,mcp:[...draft.mcp,{id:name,command:command.trim(),args:a,enabled:true}]});setName('');setCommand('');setArgs('[]');setError('');}catch(e){setError(String(e));}}}>添加 MCP</button>{error&&<p role="alert">{error}</p>}{draft.mcp.map((m,i)=><div className="wb-row" key={i}><div><b>{m.id}</b><small>{m.command} {JSON.stringify(m.args)}</small></div><div className="wb-actions"><label><input type="checkbox" checked={m.enabled} onChange={e=>change({...draft,mcp:draft.mcp.map((v,j)=>j===i?{...v,enabled:e.target.checked}:v)})}/>启用</label><button onClick={()=>change({...draft,mcp:draft.mcp.filter((_,j)=>i!==j)})}>移除</button></div></div>)}</section>
 </>;}
function sessionTitle(s:NonNullable<Snapshot['sessions']>[number]){const title=s.projections?.title;return typeof title==='string'?title:s.blank?'空会话 / 装配检查':s.sessionId;}
function SessionList({data,sessionId,select,open}:{data:Snapshot;sessionId:string;select:(id:string)=>void;open:Open}){return <section className="wb-card"><h2>此模式的会话 <small>{data.sessionTotal??0}</small></h2><p className="wb-muted">按真实版本归属筛选，最多显示最近 100 条。选择一条查看其自身记录。</p>{!data.sessions?.length&&<p>暂无会话。先发布并开始对话，或加载检查。</p>}{data.sessions?.map(s=><div className="wb-row" key={s.sessionId}><div><strong>{sessionTitle(s)}</strong><small>{s.sessionId} · {s.running?'运行中':s.blank?'尚未执行任务':'未在运行'} · {s.projections?.agentPreset}</small></div><div className="wb-actions"><button className={s.sessionId===sessionId?'primary':''} onClick={()=>select(s.sessionId)}>查看观测</button><button onClick={()=>open(s.sessionId)}>打开对话</button></div></div>)}</section>;}
